#pragma once
#include <forest/container/literal_pair.hpp>
#include <forest/container/literal_string.hpp>
#include <forest/container/literal_tree.hpp>
#include <forest/container/literal_vector.hpp>
#include <forest/container/map.hpp>
#include <forest/container/semiregular_box.hpp>
#include <forest/container/tree.hpp>
#include <forest/container/vector.hpp>